### ISSUE TITLE
Introduce support for encoding rleD resources.

### ISSUE THREAD

**Issue by tjhancocks** [tjhancocks/kdl#10]
There needs to be a way to encode rleD resources for use in EV Nova. Due to how rleD resources work, this will need some adjustment to the KDL language and syntax.

rleD resources consist of a series of "frames" which can be thought of as separate images. Each frame should be defined as a separate image on the users system, and specified using the following
syntax:

```kdl
Sprites = import "frame1.tga" "frame2.tga" "frame3.tga" ...
```

This list should be variable in length with the user being able to specify as many as they want. Alternatively the following syntax should also be available:

```kdl
Sprites = import directory "path/to/directory" "tga"
```

This would allow the user to specify the directory containing the sprite images and specify the file extension of those images. KDL can then use this information to determine what images to load.

Once images have been loaded the following checks _must_ be completed:

1: All images must be the same size.
2: Images must support alpha transparency i.e. TGA or PNG (assuming it has been implemented)

Once everything is loaded and confirmed to be valid for an rleD frame, then the images need to be handed to the rleD encoder and processed. See how the `graphite::qd::pict` and `graphite::qd::cicn` resources work for this.

---

**Note**: Some of this work actually needs to happen in _Graphite_ rather than KDL itself.

---

**Comment by bendyer** [comment]
Graphite side completed in https://github.com/TheDiamondProject/Graphite/pull/3
