### ISSUE TITLE
Optional fields

### ISSUE THREAD

**Issue by tjhancocks** [tjhancocks/kdl#27]
Some types such as `MacintoshPicture` need this feature. They need to have multiple fields that reference the same template field, but only one needs to be specified.

```kdl
@type MacintoshPicture : "PICT" {
	template {
		HEXD Data;
	};

	optional field("PNG") {
		Data as File<PNG> __conversion($InputFile, PICT);
	};

	optional field("TGA") {
		Data as File<TGA> __conversion($InputFile, PICT);
	};
};

declare MacintoshPicture {
	new (#128) {
		PNG = import "image.png";
	};
	new (#129) {
		TGA = import "image.tga";
	};
};

```

**Comment by bendyer** [comment]
The following seems to work as-is in master:

```
@type MacintoshPicture : "PICT" {
    template {
        HEXD Data;
    };

    field("PNG") {
        Data as File<PNG> __conversion($InputFormat, PICT);
    };

    field("TGA") {
        Data as File<TGA> __conversion($InputFormat, PICT);
    };
};

declare MacintoshPicture {
    new(#128) {
        TGA = import "@rpath/TestImage.tga";
    };

    new(#129) {
        PNG = import "@rpath/TestImage.png";
    };
};
```

What would the `optional` syntax be doing—would it be used for validation, to ensure that at least one of the fields that references the `Data` binary field is specified?

**Comment by tjhancocks** [comment]
My main thinking is to make this explicit, but if it works as is... then this issue could probably be adjusted to make the optional keyword an optional requirement, or to only allow 1 field to reference a given template field.

One place it may be an issue with implicitly handling this is the disassembly stuff I'm working on, but we'll see.

Not sure... what's your thoughts on this.

**Comment by tjhancocks** [comment]
Closing this for now. Can be revisited if it becomes an issue again in the future.
